# Generated by Django 4.1.1 on 2022-09-13 09:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(default="No Title", max_length=100)),
                ("file", models.FileField(upload_to="files")),
            ],
            options={
                "ordering": ("created_at", "updated_at"),
                "abstract": False,
            },
        ),
    ]
